/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.codigodoprojeto.telas;

import com.mycompany.codigodoprojeto.modelos.Usuario;
import com.mycompany.codigodoprojeto.persistencia.DAO;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class LoginTela extends javax.swing.JFrame {
  
  private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginTela.class.getName());

  /**
   * Creates new form LoginTela
   */
  public LoginTela() {
    super("Gerenciamento Acadêmico");
    initComponents();
    setLocationRelativeTo(null);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jPanel2 = new javax.swing.JPanel();
    jLabel6 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    jLabel9 = new javax.swing.JLabel();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    emailTextField = new javax.swing.JTextField();
    senhaPasswordField = new javax.swing.JPasswordField();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    entrarButton = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setPreferredSize(new java.awt.Dimension(800, 500));

    jPanel1.setBackground(new java.awt.Color(255, 255, 255));
    jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
    jPanel1.setLayout(null);

    jPanel2.setBackground(new java.awt.Color(41, 41, 41));
    jPanel2.setPreferredSize(new java.awt.Dimension(400, 500));

    jLabel6.setFont(new java.awt.Font("Arial", 0, 19)); // NOI18N
    jLabel6.setForeground(new java.awt.Color(255, 255, 255));
    jLabel6.setText("© 2025 - Todos os direitos reservados.");

    jLabel7.setFont(new java.awt.Font("Arial", 1, 50)); // NOI18N
    jLabel7.setForeground(new java.awt.Color(102, 178, 255));
    jLabel7.setText("G.L.D.C.");

    jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Downloads\\logo.png")); // NOI18N

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel2Layout.createSequentialGroup()
            .addGap(97, 97, 97)
            .addComponent(jLabel7))
          .addGroup(jPanel2Layout.createSequentialGroup()
            .addGap(34, 34, 34)
            .addComponent(jLabel6))
          .addGroup(jPanel2Layout.createSequentialGroup()
            .addGap(150, 150, 150)
            .addComponent(jLabel9)))
        .addContainerGap(36, Short.MAX_VALUE))
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
        .addContainerGap(149, Short.MAX_VALUE)
        .addComponent(jLabel9)
        .addGap(18, 18, 18)
        .addComponent(jLabel7)
        .addGap(112, 112, 112)
        .addComponent(jLabel6)
        .addGap(59, 59, 59))
    );

    jPanel1.add(jPanel2);
    jPanel2.setBounds(0, 0, 400, 500);

    jLabel1.setFont(new java.awt.Font("Arial", 1, 39)); // NOI18N
    jLabel1.setText("Seja bem-vindo(a)");
    jPanel1.add(jLabel1);
    jLabel1.setBounds(430, 20, 340, 40);

    jLabel2.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
    jLabel2.setText("E-mail");
    jPanel1.add(jLabel2);
    jLabel2.setBounds(440, 100, 85, 30);

    jLabel3.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
    jLabel3.setText("Senha");
    jPanel1.add(jLabel3);
    jLabel3.setBounds(440, 210, 75, 30);
    jPanel1.add(emailTextField);
    emailTextField.setBounds(440, 130, 320, 40);

    senhaPasswordField.setPreferredSize(new java.awt.Dimension(64, 22));
    jPanel1.add(senhaPasswordField);
    senhaPasswordField.setBounds(440, 240, 320, 40);

    jLabel4.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
    jLabel4.setText("Criar uma conta");
    jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jPanel1.add(jLabel4);
    jLabel4.setBounds(440, 290, 130, 21);

    jLabel5.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
    jLabel5.setText("Esqueci a senha");
    jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jPanel1.add(jLabel5);
    jLabel5.setBounds(630, 290, 140, 16);

    entrarButton.setBackground(new java.awt.Color(41, 41, 41));
    entrarButton.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
    entrarButton.setForeground(new java.awt.Color(255, 255, 255));
    entrarButton.setText("Entrar");
    entrarButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        entrarButtonActionPerformed(evt);
      }
    });
    jPanel1.add(entrarButton);
    entrarButton.setBounds(530, 400, 120, 50);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void entrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarButtonActionPerformed
    // TODO add your handling code here:
    
    String email = emailTextField.getText();
    String senha = new String(senhaPasswordField.getPassword());
    
    try {
      Usuario usuario = new Usuario(email, senha);
      DAO dao = new DAO();
      
      if (dao.existeUsuario(usuario)) {
        JOptionPane.showMessageDialog(null, "Login efetuado com sucesso!");
      } else {
        JOptionPane.showMessageDialog(null, "Usuário/senha inválido!");
      }
      
    } catch(Exception e) {
      JOptionPane.showMessageDialog(null, "Tente novamente mais tarde!");
    }
  }//GEN-LAST:event_entrarButtonActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
      logger.log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> new LoginTela().setVisible(true));
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextField emailTextField;
  private javax.swing.JButton entrarButton;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPasswordField senhaPasswordField;
  // End of variables declaration//GEN-END:variables
}
